import { Geist, Geist_Mono, Oswald, Roboto } from "next/font/google";
import {
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import Navbar from "../components/ui/Navbar";
import Footer from "../components/ui/FooterSection";
import { Toaster } from "../../components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights needed
  variable: "--font-oswald", // Define a CSS variable
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} ${roboto.variable} antialiased`}
      >
        {children}
      
      </body>
    </html>
   
  );
}
